import React, { useState, useEffect, useRef } from 'react';
import { X, Linkedin, Sparkles, Copy, Check, Loader2, AlertCircle, User, FileText, Settings } from 'lucide-react';
import { supabase } from '../supabaseClient';
import useAuth from '../hooks/useAuth';
import * as pdfjsLib from 'pdfjs-dist/build/pdf.min.mjs';
import pdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';

pdfjsLib.GlobalWorkerOptions.workerSrc = pdfWorker;


const RecruiterMessageModal = ({ isOpen, onClose, job }) => {
    const { user } = useAuth();
    const resultRef = useRef(null);
    const hasAutoGenerated = useRef(false);

    // Resume from Settings (profiles table)
    const [resumeUrl, setResumeUrl] = useState(null);
    const [resumeFileName, setResumeFileName] = useState('');
    const [isLoadingResume, setIsLoadingResume] = useState(false);

    // Generation state
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedMessage, setGeneratedMessage] = useState('');
    const [copied, setCopied] = useState(false);
    const [error, setError] = useState(null);
    const [fullJobDescription, setFullJobDescription] = useState(job?.description || '');
    const [isFetchingDesc, setIsFetchingDesc] = useState(false);

    const extractNameFromLinkedInUrl = (url) => {
        if (!url) return 'Recruiter';
        try {
            const match = url.match(/\/in\/([^/?#]+)/);
            if (match && match[1]) {
                let namePart = match[1];
                namePart = namePart.replace(/-[a-zA-Z0-9]{8,}$/, '');
                return namePart.split('-')
                    .filter(part => part.length > 0)
                    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
                    .join(' ');
            }
        } catch (e) {}
        return 'Recruiter';
    };

    // On open: load job description + resume URL from Settings
    useEffect(() => {
        if (!isOpen) return;
        setGeneratedMessage('');
        setError(null);
        setCopied(false);
        hasAutoGenerated.current = false; // Reset on open

        if (job && !job.description && !fullJobDescription) fetchFullDescription();
        if (user) fetchResumeFromSettings();
    }, [isOpen, job, user]);

    // Auto-generate once both description and resume are ready
    useEffect(() => {
        if (isOpen && resumeUrl && fullJobDescription && !isGenerating && !generatedMessage && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            generateMessage();
        }
    }, [isOpen, resumeUrl, fullJobDescription, isGenerating, generatedMessage]);

    useEffect(() => {
        if (generatedMessage && resultRef.current) {
            resultRef.current.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }
    }, [generatedMessage]);

    const fetchFullDescription = async () => {
        setIsFetchingDesc(true);
        try {
            const jobId = job.job_id || job.id;
            const { data } = await supabase
                .from('jobs_all_roles')
                .select('description')
                .eq('id', jobId)
                .single();
            if (data?.description) setFullJobDescription(data.description);
        } catch (err) {
            console.error('Error fetching description:', err);
        } finally {
            setIsFetchingDesc(false);
        }
    };

    const fetchResumeFromSettings = async () => {
        setIsLoadingResume(true);
        try {
            const { data } = await supabase
                .from('profiles')
                .select('resume_url')
                .eq('id', user.id)
                .single();

            if (data?.resume_url) {
                setResumeUrl(data.resume_url);
                const parts = data.resume_url.split('/');
                const raw = parts[parts.length - 1] || 'resume.pdf';
                const nameMatch = raw.match(/^[^_]+_\d+_(.+)$/);
                setResumeFileName(nameMatch ? nameMatch[1] : raw);
            } else {
                setResumeUrl(null);
                setResumeFileName('');
            }
        } catch (err) {
            console.error('Error loading resume from settings:', err);
        } finally {
            setIsLoadingResume(false);
        }
    };

    const extractTextFromPDF = async (arrayBuffer) => {
        const typedarray = new Uint8Array(arrayBuffer);
        const pdf = await pdfjsLib.getDocument({ data: typedarray }).promise;
        let text = '';
        for (let i = 1; i <= pdf.numPages; i++) {
            const page = await pdf.getPage(i);
            const content = await page.getTextContent();
            text += content.items.map(item => item.str).join(' ') + '\n';
        }
        return text;
    };

    const generateMessage = async () => {
        if (!resumeUrl) {
            setError('No resume found. Please upload your resume in Settings first.');
            return;
        }

        setError(null);
        setIsGenerating(true);
        setGeneratedMessage('');

        try {
            // 1. Download the resume from Supabase Storage URL
            const response = await fetch(resumeUrl);
            if (!response.ok) throw new Error('Failed to download your resume. Please re-upload in Settings.');
            const arrayBuffer = await response.arrayBuffer();

            // 2. Extract text
            let resumeText = '';
            const contentType = response.headers.get('content-type') || '';
            if (contentType.includes('pdf') || resumeUrl.toLowerCase().endsWith('.pdf')) {
                resumeText = await extractTextFromPDF(arrayBuffer);
            } else {
                resumeText = new TextDecoder().decode(arrayBuffer);
            }

            if (!resumeText.trim()) throw new Error('Could not read resume text. Please try re-uploading a PDF.');

            // 3. Call OpenAI
            const apiKey = import.meta.env.VITE_OPENAI_API_KEY;
            
            if (!apiKey || apiKey === 'undefined') {
                throw new Error("OpenAI API key is missing. Please restart your 'npm run dev' terminal to load the updated .env file.");
            }

            const aiResponse = await fetch('/api/openai/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${apiKey}`
                },
                body: JSON.stringify({
                    model: 'gpt-4o',
                    messages: [
                        { role: 'system', content: 'You are an expert career coach helping a job candidate write a highly effective cold-outreach message to a recruiter.' },
                        {
                            role: 'user',
                            content: `Write a direct message FROM the candidate TO the recruiter based on:

1. The candidate's resume (provided below).
2. The job details provided below.

Job Details:
* Job Title: ${job.title || 'Not specified'}
* Company: ${job.company || 'Not specified'}
* Location: ${job.location || 'Not specified'}
* Job Description: ${fullJobDescription || 'Not specified'}
* Recruiter Name: ${extractNameFromLinkedInUrl(job.posted_by_profile)}

Instructions:
* Start the message exactly with "Hi [Recruiter Name]," (use the Recruiter Name provided above).
* Do NOT start the message with the candidate's name.
* Write entirely in the first person ("I") as the candidate reaching out regarding the opportunity.
* Thoroughly analyze the resume to highlight the candidate's strongest matching skills for this specific role.
* Keep the message professional, confident, and concise.
* Avoid generic job-seeking language. Do not invent experience.
* End with a professional call to action.

Output Requirements:
* Strictly between 250 and 300 characters.
* Plain text only. No headings, bullet points, or placeholders.
* Return ONLY the final message content.

Candidate's Resume Text:
${resumeText}`
                        }
                    ],
                    temperature: 0.7
                })
            });

            if (!aiResponse.ok) {
                const errorData = await aiResponse.json().catch(() => null);
                console.error("OpenAI Error:", errorData);
                const apiErrorMsg = errorData?.error?.message || `HTTP ${aiResponse.status} - Failed to generate message from AI.`;
                throw new Error(apiErrorMsg);
            }

            const data = await aiResponse.json();
            if (data.choices?.length > 0) {
                setGeneratedMessage(data.choices[0].message.content.trim());
            } else {
                throw new Error('Invalid response from AI. No choices returned.');
            }
        } catch (err) {
            console.error('Generation error:', err);
            setError(err.message || 'An error occurred while generating the message.');
        } finally {
            setIsGenerating(false);
        }
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(generatedMessage);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 overflow-y-auto bg-black/60 backdrop-blur-sm">
            <div className="min-h-full flex items-center justify-center p-4">
                <div className="bg-white rounded-[24px] w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col my-4 md:my-8">

                    {/* Header */}
                    <div className="flex items-center justify-between px-4 md:px-6 py-4 md:py-5 border-b border-gray-100 bg-gray-50/50">
                        <div className="flex items-center gap-3">
                            <div className="w-10 h-10 rounded-full bg-blue-600/10 flex items-center justify-center">
                                <Linkedin className="text-blue-600" size={20} />
                            </div>
                            <div>
                                <h2 className="text-lg font-black text-gray-900 leading-tight">Message Recruiter</h2>
                                <p className="text-sm font-semibold text-gray-500">Generate an impactful introduction</p>
                            </div>
                        </div>
                        <button onClick={onClose} className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-full transition-colors">
                            <X size={20} strokeWidth={2.5} />
                        </button>
                    </div>

                    {/* Body */}
                    <div className="p-4 md:p-6">

                        {/* Recruiter Info */}
                        <div className="mb-5 p-4 bg-white border border-gray-100 shadow-sm rounded-xl flex items-center justify-between hover:shadow-md transition-shadow">
                            <div>
                                <p className="text-[12px] font-bold text-gray-400 mb-1 uppercase tracking-wider">Recruiter</p>
                                <a
                                    href={job.posted_by_profile}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-[16px] font-black text-blue-600 hover:text-blue-600/80 flex items-center gap-2 transition-colors"
                                >
                                    <User size={18} className="text-blue-600/60 fill-current" />
                                    {extractNameFromLinkedInUrl(job.posted_by_profile)}
                                </a>
                            </div>
                        </div>

                        {/* Status / Loading */}
                        {(!generatedMessage && !error) && (
                            <div className="flex flex-col items-center justify-center p-8 bg-blue-50/50 rounded-xl border border-blue-100 mb-6 text-center animate-pulse">
                                <Loader2 className="w-8 h-8 text-blue-600 animate-spin mb-3" />
                                <h3 className="text-sm font-bold text-blue-900 mb-1">Crafting your message...</h3>
                                <p className="text-xs text-blue-600/80 font-medium">Analyzing your resume and the job description</p>
                            </div>
                        )}

                        {/* Error State */}
                        {error && (
                            <div className="mb-6 p-4 bg-red-50 border border-red-200 text-red-700 rounded-xl flex items-start gap-3">
                                <AlertCircle size={20} className="shrink-0 mt-0.5 text-red-500" />
                                <div className="text-sm font-medium leading-relaxed">
                                    <p className="font-bold mb-1">Message Generation Failed</p>
                                    <p>{error}</p>
                                    {!resumeUrl && (
                                        <p className="mt-2 text-red-600 text-xs">
                                            Please go to <strong>Settings → Profile → Resume</strong> to upload a resume first.
                                        </p>
                                    )}
                                </div>
                            </div>
                        )}

                        {/* Result */}
                        {generatedMessage && (
                            <div ref={resultRef} className="animate-fadeIn pb-4">
                                <h3 className="text-[13px] font-bold text-gray-900 mb-3 uppercase tracking-wider">Your Message</h3>
                                <div className="relative group bg-white border-2 border-gray-100 rounded-2xl shadow-sm transition-all overflow-hidden">
                                    <div
                                        className="w-full min-h-[12rem] p-4 md:p-5 text-[14px] font-medium text-gray-900 leading-relaxed whitespace-pre-wrap select-text"
                                        style={{ paddingTop: '56px', paddingBottom: '16px' }}
                                    >
                                        {generatedMessage}
                                    </div>
                                    <button
                                        onClick={copyToClipboard}
                                        style={{ position: 'absolute', top: '12px', right: '12px' }}
                                        className={`p-2 rounded-xl shadow-sm transition-all flex items-center gap-2 font-bold text-[12px] ${copied ? 'bg-green-500 text-white' : 'bg-gray-50 border border-gray-200 text-gray-600 hover:text-blue-600 hover:border-blue-600 hover:bg-white'}`}
                                    >
                                        {copied ? <><Check size={14} strokeWidth={3} /> Copied!</> : <><Copy size={14} /> Copy</>}
                                    </button>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default RecruiterMessageModal;
